blog/main/models.py
# 渲染项目不需要 models

blog/main/__init__.py
from flask import Flask, g

from main.ext import init_ext
from main.views import init_view


def create_app(env):
    app = Flask(__name__, static_folder='static')
    app.config.from_object(env)
    init_view(app)
    init_ext(app)

    return app

blog/main/views/__init__.py
from main.views.api import blue


def init_view(app):
    app.register_blueprint(blue)

blog/main/views/api.py
import datetime
import os
import uuid

from flask import Blueprint, request, render_template, jsonify, flash, redirect, url_for, session, g

from main.settings import BASE_DIR

blue = Blueprint('blue', __name__)


@blue.route('/')
def index():
    return render_template('index.html')


@blue.route('/register/')
def register():
    return render_template('register.html')


@blue.route('/login/', methods=['GET', 'POST'])
def login():
    return render_template('login.html')


@blue.route('/logout/')
def logout():
    return redirect(url_for('blue.login'))


@blue.route('/verified/')
def verified():
    return render_template('verified.html')


@blue.route('/admin/')
def admin():
    # 应该显示主页，主页显示有待审核的文章数量，点击数量进入待审核页面
    return render_template('admin/getTypes.html')


@blue.route('/admin/login/')
def admin_login():
    return render_template('login.html')


@blue.route('/admin/addtypes/')
def admin_add_types():
    return render_template('admin/addTypes.html')


@blue.route('/admin/gettypes/')
def admin_get_types():
    return render_template('admin/getTypes.html')


@blue.route('/admin/ganvas/')
def ganvas():
    return render_template('admin/ganvas.html')


@blue.route('/publish/')
def publish_new_blog():
    return render_template('blog/newBlog.html')


@blue.route('/upload/', methods=['POST'])
def upload_img():
    os.chdir(os.path.join(BASE_DIR, 'main/static/img'))
    img = request.files.get('img')
    old_name = img.filename.split('.')
    suffix = old_name[-1]
    now = datetime.datetime.now()
    today = datetime.datetime.strftime(now, '%Y%m%d')
    filename = uuid.uuid4().hex
    if not os.path.exists(today):
        os.makedirs(today, 755)
    img.save(f'{today}/{filename}.{suffix}')
    return jsonify(
        {'msg': 'the image has uploaded successful.', 'filename': f'{today}/{filename}.{suffix}',
         'oldName': old_name[0]})


@blue.route('/blog/<int:id>/')
def blog(id):
    text = request.form
    print(text)
    return render_template('blog/blog.html')


@blue.route('/user/<int:id>/')
def user(id):
    return render_template('user/userBlog.html')


@blue.route('/myblog/')
def my_blog():
    return render_template('user/myBlog.html')


@blue.route('/comments/<int:id>')
def my_comments(id):
    return render_template('user/myComments.html')


@blue.route('/type/<int:id>/')
def type_blog(id):
    return render_template('blog/typeBlog.html')


@blue.route('/myfavorite/')
def my_favorite():
    return render_template('user/myFavorite.html')


@blue.route('/account/')
def account():
    return render_template('user/account.html')


@blue.route('/audit/<int:id>/')
def audit(id):
    return render_template('admin/audit.html')


@blue.route('/search/')
def search():
    return render_template('search.html')

blog/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}

    {% endblock %}
    <link rel="icon" href="{{ url_for('static',filename='favicon.ico') }}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <style>
        body {
            background-color: #dedede;
        }

        .content {
            position: absolute;
            background-color: white;
            width: 1140px;
            height: 840px;
            left: 382.5px;
            padding: 0 10px;
        }
    </style>
    {% block style %}

    {% endblock %}
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('blue.index') }}" class="navbar-brand" title='回到主页'><img id="logo"
                                                                            src="{{ url_for('static',filename='favicon.ico') }}"
                                                                            alt=""></a>
            <a class="navbar-brand" href="{{ url_for('blue.index') }}"  title='回到主页'>无空的博客</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% block index %}
                    <li><a href="/"  title='回到主页'>主页</a></li>
                {% endblock %}
                {#                <li><a href="#">关于</a></li>#}
                <li><a href="mailto:thepoy@163.com">联系我</a></li>
            </ul>
            <form class="navbar-form navbar-left" id="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="搜索标题、内容或作者" id="search-input">
                </div>
                <button type="button" class="btn btn-default">搜索</button>
            </form>
            <ul class="nav navbar-nav navbar-right" id="topbar-right">
                {#                <li class="types" id=""><a href="#">文章类型</a></li>#}
                <li class="dropdown" id="types">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">文章类型 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    </ul>
                </li>

                <li class="types" id="login"><a href="{{ url_for('blue.login') }}">登录</a></li>
                <li class="types" id="register"><a href="{{ url_for('blue.register') }}">注册</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

{% block sidebar %}

{% endblock %}

<div class="content">
    {% block content %}

    {% endblock %}
</div>


<script type="text/javascript" src="{{ url_for('static',filename='js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/base.js') }}"></script>

{% block js %}
{% endblock %}
</body>
</html>

blog/main/templates/blog/blog.html
{% extends 'base.html' %}

{% block title %}
    当前文章
{% endblock %}


{% block style %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/blog/markdownhere.css') }}">
    <style>
        .content {
            padding-top: 20px;
            height: auto;
        }

        #navbar li {
            margin: 0;
        }

        div.newBlog {
            position: absolute;
            width: 1100px;
            height: 30px;
            top: 20px;
            left: 20px;
        }

        #title {
            width: 600px;
        }

        div.typeTitle {
            position: relative;
            top: 0;
            height: 29px;
        }

        div.type {
            float: left;
            margin: 1px;
        }

        div.type label {
            margin-top: 4px;
        }

        #type {
            height: 29px;
        }

        div.title {
            float: right;
        }

        #area {
            width: 1140px;
            margin-left: -10px;
            border: #888888 5px;
            border-style: solid none;
        }

        #area td {
            width: 1140px;
        }

        div.uploadIMG {
            position: absolute;
            left: 520px;
            top: 50px;
        }

        #upload-img-icon:hover {
            cursor: pointer;
        }

        #show-area img {
            width: 1110px;
        }

        #show-area {
            width: 1120px;
            margin-left: 10px;
        }

        #show-area img {
            border-radius: 3px;
            box-shadow: rgba(0, 0, 0, 0.15) 0 0 8px;
            background: #FBFBFB;
            border: 1px solid #ddd;
            margin: 20px 0;
        }

        #title, #author {
            text-align: center;
            margin: 0 auto;
        }

        #title {
            font-size: 26px;
            font-weight: bold;
        }

        #author {
            margin: 5px 0 5px 0;
        }

        #author a {
            color: #8c8c8c;
        }

        #publishTime {
            color: #8c8c8c;
            text-align: right;
            margin: 0 auto 0 auto;
        }

        #addComment {
            width: 1120px;
            height: 150px;
        }

        #publishAddComment {
            display: block;
            margin: 0 auto 0 1030px;
        }

        .commentsArea {
            font-weight: bold;
            font-size: 18px;
        }

        .comment {
            border: #8c8c8c 1px;
            border-style: solid none;
            margin: -1px 0 0 -1px;
        }

        .pi {
            float: right;
            margin-right: 20px;
            margin-top: 10px;
            font-size: 13px;
        }

        .comment-info, .pages {
            text-align: right;
            margin: 0 auto 10px auto;
            font-size: 13px;
        }

        .pages {
            margin-top: 20px;
        }

        .comment-publish-time, .type {
            color: #8c8c8c;
        }

        blockquote {
            font-size: 14px;
        }

        .edit-comments {
            display: inline-block;
            float: left;
            margin-left: 20px;
        }

        #edit-blog {
            margin: 20px auto auto 20px;
        }

        input#title {
            font-size: 16px;
            font-weight: normal;
            text-align: left;
            width: 600px;
            margin-left: 270px;
        }

        textarea#show-area {
            height: 800px;
            font-size: 15px;
            margin-bottom: 40px;
            overflow-y: scroll;
        }

        button#confirm, button#cancel {
            position: relative;
            right: -1000px;
            top: -20px;
        }

        #favorite {
            display: block;
            margin-top: -30px;
            margin-bottom: 20px;
            margin-left: 531px;
        }

        #delete-favorite {
            display: block;
            margin-top: -30px;
            margin-bottom: 20px;
            margin-left: 516px;
        }

        #manage-blog {
            margin-bottom: -20px;
        }

        #deleted {
            left: 90px;
        }

        .manage-comment label {
            margin-left: 40px;
        }

        #reason {
            width: 400px;
        }

        #confirm-reason {
            margin-left: 20px;
        }

        .manage-comment {
            display: inline-block;
            float: left;
        }

        #comments-area .clearfix {
            padding-left: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="type"></div>
    <div id="title"></div>
    <div id="author" class="author"></div>
    <div id="publishTime"></div>
    <div id="area">
        <div id="show-area" class="clearfix"></div>
    </div>
    <br>
    <br>
    <div class="addComment">
        <textarea name="addComment" id="addComment" autofocus></textarea>
        <span style="display: inline-block; float: left;color: #8c8c8c;">（注意：快捷回复支持Markdown，暂不支持实时预览。如果你对Markdown不熟悉可直接回复文本。<br>&nbsp;&nbsp;&nbsp;&nbsp;进行快捷回复时，请勿移动光标位置，否则可能会导致排版混乱）</span>
        <button id="publishAddComment">发布评论</button>
    </div>
    <p class="commentsArea">评论区：</p>
    <div id="comments-area"></div>
    <div class="pages"></div>
{% endblock %}


{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/showdown.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='js/blog.js') }}"></script>
{% endblock %}

blog/main/templates/blog/newBlog.html
{% extends 'base.html' %}

{% block title %}
    写新文章
{% endblock %}


{% block style %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/blog/markdownhere.css') }}">
    <style>
        .content {
            height: 880px;
        }

        #navbar li {
            margin: 0;
        }

        div.newBlog {
            position: absolute;
            width: 1100px;
            height: 30px;
            top: 20px;
            left: 20px;
        }

        #title {
            width: 600px;
        }

        div.typeTitle {
            position: relative;
            top: 0;
            height: 29px;
        {#background: #d5d5d5;#}
        }

        div.type {
            float: left;
            margin: 1px;
        }

        div.type label {
            margin-top: 4px;
        }

        #type {
            height: 29px;
        }

        div.title {
            float: right;
        }

        #area {
            position: absolute;
            top: 70px;
            width: 1100px;
        }

        #md-area {
            height: 700px;
            width: 529px;
        }

        #show-area {
            height: 700px;
            width: 528px;
            overflow-y: scroll;
        }

        .btn-primary {
            position: absolute;
            margin: 10px 0 0 20px;
            text-shadow: black 0 0.1em 0.2em;
            width: 100px;
            bottom: 5px;
            right: 20px;
        }

        #isPrivate {
            position: absolute;
            bottom: 7px;
            right: 150px;
        }

        #htmlText, #MDText {
            position: absolute;
            top: 50px;
        }

        #MDText {
            right: 0;
        }

        .line1, .line2 {
            position: absolute;
            width: 1140px;
            border: #888888 1px double;
            left: -20px;
        }

        .line1 {
            top: -13px;
        }

        .line2 {
            top: 40px;
        }

        div.uploadIMG {
            position: absolute;
            left: 520px;
            top: 50px;
        }

        #upload-img-icon:hover {
            cursor: pointer;
        }

        #show-area img {
            width: 1240px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="newBlog">
        <div class="typeTitle">
            <div class="type">
                <label for="type">类别：</label>
                <select name="type" id="type">
                </select>
            </div>
            <div class="title">
                <label for="title">标题：</label>
                <input type="text" id="title" name="title" placeholder="新文章标题"><span>(长度限制为40个字符)</span>
            </div>
        </div>
        <div class="line1"></div>
        <div class="line2"></div>
        <div id="htmlText">
            <span>这里输入MarkDown原文：</span>
        </div>
        <div class="uploadIMG">
            <label for="upload-img"><span id="upload-img-icon" class="glyphicon glyphicon-picture" title="上传图片"></span></label>
            <input type="file" id="upload-img" name="upload-img" accept="image/gif, image/jpeg, image/png, image/jpg">
        </div>
        <div id="MDText">
            <span>这里输出HTML：</span>
        </div>
        <div id="area">
            <table>
                <tr>
                    <td><textarea name="" id="md-area" onkeyup=mdSwitch()></textarea></td>
                    <td>
                        <div id="show-area" class="clearfix"></div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="isPrivate">
        <label for="private">是否保存为私密文章</label>
        <input type="checkbox" name="private" id="private" value="1">
    </div>
    <button class="btn btn-primary" id="publishNewBlog">发布</button>

{% endblock %}


{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/showdown.min.js') }}"></script>
    <script>
        function mdSwitch() {
            var mdValue = document.getElementById("md-area").value;
            var converter = new showdown.Converter();
            var html = converter.makeHtml(mdValue);
            document.getElementById("show-area").innerHTML = html;
        }

        let allTypes = $('#type')
        $.ajax({
            type: 'GET',
            url: 'http://<your host/your domain>/api/types/',
            success: function (data) {
                let html = '<option value=0>选择文章类型</option>'
                $.each(data.data, function (index, value) {
                    html += '<option value=' + value.id + '>' + value.type + '</option>'
                })
                allTypes.html(html)
            }
        })

        $('#upload-img').change(function () {
            let img = $('#upload-img').prop('files')[0]
            let formData = new FormData()
            formData.append('name', $("#id_name").val())
            formData.append('img', img)
            $.ajax({
                type: 'POST',
                url: '/upload/',
                processData: false,
                contentType: false,
                data: formData,
                success: function (data) {
                    let mdArea = $('#md-area')
                    let mdText = mdArea.val()
                    console.log(mdArea.rows)
                    let imgUrl = '![' + data.oldName + ']' + '(http://<your host/your domain>/static/img/' + data.filename + ')'
                    mdArea.val(mdText + imgUrl)
                }
            })
        })
        $('#publishNewBlog').click(function () {
            let $title = $('#title')
            let title = $title.val().trim()
            let type = $('#type').val()
            if (type == 0) {
                alert('请选择文章类型')
            } else {
                if (!title) {
                    alert('标题不能为空')
                    /* 还得限制标题长度不能超过40个字符 */
                } else {
                    console.log(title.length)
                    if (title.length > 40) {
                        alert('标题字符数量不能超过40个字符！')
                    } else {
                        let isPrivate = $('#private').prop('checked')
                        let mdArea = $('#md-area')
                        let mdText = mdArea.val()
                        if (mdText.length < 2) {
                            alert('内容最少包含2个字符！')
                        } else {
                            if (!isPrivate) { /* ajax传递的bool值会转换为字符串，对python来说所有的非空字符串都是true，只需将false的bool值赋予空字符串就行 */
                                isPrivate = ''
                            }
                            $.ajax({
                                type: 'POST',
                                url: 'http://<your host/your domain>/api/blogs/?token=' + getToken(),
                                data: {
                                    type: type,
                                    title: title,
                                    content: mdText,
                                    is_private: isPrivate
                                },
                                success: function (data) {
                                    location.href = data.data.url
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    let err = jqXHR.responseText
                                    let msg = JSON.parse(err)
                                    alert(msg.error || JSON.stringify(msg.message).replace('{', '').replace('}', ''))
                                },
                            })
                        }
                    }
                }
            }
        })
    </script>
{% endblock %}

blog/main/templates/blog/typeBlog.html
{% extends 'index.html' %}

{% block title %}

{% endblock %}

{% block style %}
    {{ super() }}
    <style>
        #typeBlogTile {
            position: absolute;
            top: 20px;
            left: 20px;
            font-weight: bold;
            font-size: 26px;
        }

        #noBlog {
            font-size: 20px;
            font-style: oblique;
            font-weight: bold;
            position: absolute;
            left: 490px;
            top: 400px;
            color: #9d9d9d;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/typeBlog.js') }}"></script>
{% endblock %}

blog/main/templates/index.html
{% extends 'base.html' %}

{% block title %}
    主页
{% endblock %}

{% block style %}
    <style>
        .content {
            height: 964px;
        }

        .titleBar {
            position: absolute;
            width: 1100px;
            height: 30px;
            left: 20px;
        }

        .titleBar {
            top: 70px;
        }

        .blogList {
            position: absolute;
            width: 1140px;
            height: 30px;
            top: 100px;
            background-color: white;
            left: 0;
        }

        .titleBar a {
            pointer-events: none;
        }

        .btn-primary {
            position: absolute;
            top: 20px;
            left: 20px;
            text-shadow: black 0 0.1em 0.2em;
        }

        div.pages {
            position: absolute;
            left: 740px;
            width: 400px;
            height: 30px;
            text-align: right;
            margin: 0 auto 10px auto;
            font-size: 13px;
            padding-right: 20px;
        }

        div.top {
            top: 25px;
            color: white;
        }

        div.bottom {
            bottom: 5px;
        }

        div.titleBtns, div.blog {
            height: 100%;
            background: #888888;
            text-align: center;
            float: left;
            line-height: 18px;
            border: #d5d5d5 2px double;
            margin: 0 -2px -2px 0;

        }

        div.blog {
            border: #d5d5d5 1px solid;
            background: white;
            height: 40px;
        }


        div.titleBtns a, div.blogOverview a {
            display: inline-block;
            height: 18px;
            line-height: 16px;
            margin-top: 5px;
            color: white;
            text-shadow: black 0 0.1em 0.2em;
        }

        div.blogOverview {
            height: 40px;
            background-color: white;
            padding-left: 20px;
        }

        div.blogOverview a {
            margin-top: 10px;
            color: black;
            text-shadow: none;
        }

        a.typeBtn {
            width: 80px;
        }

        a.titleBtn {
            width: 588px;
        }

        a.authorBtn {
            width: 100px;
        }

        a.publishTimeBtn {
            width: 120px;
        }

        a.commentsCountBtn {
            width: 80px;
        }

        a.newCommentTimeBtn {
            width: 120px;
        }

        a.type {
            width: 82px;
        }

        a.title {
            width: 591px;
        }

        a.author {
            width: 101px;
        }

        a.publishTime {
            width: 123px;
            pointer-events: none;
        }

        a.commentsCount {
            width: 81px;
        }

        a.newCommentTime {
            width: 122px;
        }
    </style>
{% endblock %}

{% block index %}
    <li class="active"><a href="/">主页</a></li>
{% endblock %}

{% block content %}
    <button class="btn btn-primary" id="publishNewBlog">发布新文章</button>
    <div class="pages top">
    </div>
    <div class="titleBar">
        <div class="titleBtns"><a href="javascript:" class="typeBtn">类型</a></div>
        <div class="titleBtns"><a href="javascript:" class="titleBtn">标题</a></div>
        <div class="titleBtns"><a href="javascript:" class="authorBtn">作者</a></div>
        <div class="titleBtns"><a href="javascript:" class="publishTimeBtn">发贴时间</a></div>
        <div class="titleBtns"><a href="javascript:" class="commentsCountBtn">评论数</a></div>
        <div class="titleBtns"><a href="javascript:" class="newCommentTimeBtn">最新评论</a></div>
    </div>
    <div class="blogList">
    </div>
    <div class="pages bottom">
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/index.js') }}"></script>
{% endblock %}

blog/main/templates/login.html
{% extends 'base.html' %}

{% block title %}
    登录
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login-and-register.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        {% for get_flashed_message in get_flashed_messages() %}
            <span style="color: red">{{ get_flashed_message }}</span>
        {% endfor %}

        <form class="form-signin" action="#" method="post">
            <h2 class="form-signin-heading">登录</h2><br>
            <label for="username" class="sr-only">用户名：</label>
            <input type="text" name="username" id="username" class="form-control" placeholder="请输入用户名、邮箱或手机号" required
                   autofocus>
            <span id="username_status"></span><br>
            <label for="password" class="sr-only">密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>
            <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码" required>
            <span id="password_status"></span><br>
            <button class="btn btn-lg btn-primary btn-block" id="submit" type="button">登录</button>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}

blog/main/templates/register.html
{% extends 'base.html' %}

{% block title %}
    注册新账号
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login-and-register.css') }}">
{% endblock %}

{% block js %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <form class="form-signin" action="#" method="post" onsubmit="return check()">
            <h2 class="form-signin-heading">注册新账号</h2><br>
            <label for="username">用户名：</label>
            <input type="text" name="username" id="username" class="form-control" placeholder="请输入用户名" autofocus>
            <span id="username_status"></span><br>
            <label for="password">密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>
            <input type="password" name="password" id="password" class="form-control" placeholder="请输入密码">
            <span id="password_status"></span><br>
            <label for="email">邮&nbsp;&nbsp;&nbsp;&nbsp;箱：</label>
            <input type="text" name="email" id="email" class="form-control" placeholder="请输入邮箱">
            <span id="email_status"></span><br>
            <label for="phone">手机号：</label>
            <input type="text" name="phone" id="phone" class="form-control" placeholder="请输入手机号">
            <span id="phone_status"></span><br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
        </form>
    </div>
{% endblock %}

blog/main/templates/search.html
{% extends 'base.html' %}

{% block title %}
    搜索结果
{% endblock %}

{% block style %}
    <style>
        .content {
            height: initial;
            padding-bottom: 60px;
        }

        #searchResultTile {
            position: absolute;
            top: 20px;
            left: 20px;
            font-weight: bold;
            font-size: 26px;
        }

        #searchCount {
            position: absolute;
            top: 35px;
            left: 130px;
            color: #9d9d9d;
        }

        .keyWord {
            color: red;
        }

        div.split-line {
            position: absolute;
            top: 60px;
            left: 0;
            height: 1px;
            width: 1140px;
            border: #b6b6b6 1px double;
        }


        div.pages {
            position: absolute;
            left: 740px;
            width: 400px;
            height: 30px;
            text-align: right;
            margin: 0 auto 10px auto;
            font-size: 13px;
            padding-right: 20px;
        }

        div.top {
            top: 25px;
            color: white;
        }

        div.bottom {
            bottom: 5px;
        }

        #result-list {
            margin-top: 70px;
        }

        #result-list ul li {
            display: inline-block;
            list-style: none;
            margin-top: 20px;
        }

        .blog-title {
            font-size: 16px;
            text-decoration: underline;
            color: #00C;
        }

        .blog-content {
            display: block;
            margin: 0;
            width: 700px;
            font-size: 13px;
        }

        .publish-time {
            color: #3A8000;
        }

        .result span a {
            color: #666;
        }
    </style>
{% endblock %}

{% block content %}
    <span id="searchResultTile">搜索结果</span><span id="searchCount"></span>
    <div class="split-line"></div>
    <div class="pages top"></div>
    <div class="pages bottom"></div>
    <div id="result-list">
        <ul>
        </ul>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/search.js') }}"></script>
{% endblock %}

blog/main/templates/user/account.html
{% extends 'base.html' %}

{% block title %}
    个人中心
{% endblock %}

{% block style %}
    <style>
        .change {
            margin-top: 40px;
            margin-bottom: 40px;
            margin-left: 250px;
            border: #888888 1px solid;
            width: 600px;
            padding-left: 100px;
            padding-top: 20px;
            padding-bottom: 20px;
        }

        label {
            text-align: justify;
            text-justify: inter-ideograph;
            width: 80px;
        }

        .change .confirm {
            margin-top: 10px;
            margin-left: 180px;
        }

        .notLogin {
            font-size: 30px;
            font-weight: bold;
            font-style: italic;
            color: #606060;
            text-shadow: #8c8c8c 1px 1px 5px;
            position: absolute;
            line-height: 50px;
            left: 525px;
            top: 395px;
        }
    </style>
{% endblock %}

{% block content %}

{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/account.js') }}"></script>
{% endblock %}

blog/main/templates/user/myBlog.html
{% extends 'index.html' %}

{% block title %}

{% endblock %}

{% block style %}
    {{ super() }}
    <style>
        #userBlogTile {
            position: absolute;
            top: 20px;
            left: 20px;
            font-weight: bold;
            font-size: 26px;
        }
    </style>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static',filename='js/myBlog.js') }}"></script>
{% endblock %}